version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

        environment:
            COVERALLS_SERVICE_NAME: "circleci"

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "package-lock.json" }}
          - v0-dependencies-
      - restore_cache:
          keys:
          - sonar-cache

      - run: npm i
      - run: sudo npm i -g sonarqube-scanner
      - run:
          name: Set Environment Variables
          command: |
            echo "export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")" >> $BASH_ENV
            source $BASH_ENV

      - save_cache:
          paths:
            - node_modules
          key: v0-dependencies-{{ checksum "package-lock.json" }}
        
      - run: 
          name: build
          command: npm run build
      - store_artifacts:
          path: .coverage/unit/
          prefix: coverage
      - store_test_results:
          path: .testresults/unit

      - run:
          name: sonar
          command: sonar-scanner -Dsonar.projectVersion=$PROJECT_VERSION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN

      - save_cache:
          paths:
            - ~/.sonar
          key: sonar-cache